CREATE DATABASE LEAVE_MANAGEMENT;

USE LEAVE_MANAGEMENT;

-- create table users
CREATE TABLE USER (
    EMAIL_ID VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL
);

-- Insert a sample user
INSERT INTO user (EMAIL_ID, password) VALUES ('anil.a@gmail.com', 'Password@#123');


-- Create todos table
CREATE TABLE TODOS (
    TODO_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TODO_NAME VARCHAR(255) NOT NULL,
    PRIORITY ENUM('High', 'Medium', 'Low') NOT NULL,
    END_DATE DATE NOT NULL,
    END_TIME TIME NOT NULL,
    IS_COMPLETED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- insert sample

INSERT INTO TODOS (USER_ID, TODO_NAME, PRIORITY, END_DATE, END_TIME, IS_COMPLETED)
VALUES (1, 'Finish the project', 'High', '2024-08-30', '15:30:00', FALSE);

-- creating index on user_id

CREATE INDEX idx_user_id ON TODOS(USER_ID);

