CREATE DATABASE LEAVE_MANAGEMENT;

USE LEAVE_MANAGEMENT;

-- CREATE TABLE LOGIN_CREDENTIALS
CREATE TABLE LOGIN_CREDENTIALS (
    EMAIL_ID VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL
);

-- INSERT INTO
INSERT INTO LOGIN_CREDENTIALS (EMAIL_ID, password) VALUES ('anil@wavemaker.com', 'Password@#123');


-- CRATE TABLE EMPLOYEES
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_NAME VARCHAR(40) NOT NULL,
    EMAIL_ID VARCHAR(40) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    MANAGER_ID INT DEFAULT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES employees(EMPLOYEE_ID) ON DELETE SET NULL
);


-- CREATE TABLE LEAVES
CREATE TABLE LEAVES (
    LEAVE_ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID INT NOT NULL,
    LEAVE_TYPE VARCHAR(50) DEFAULT NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE NOT NULL,
    APPLIED_ON DATE NOT NULL,
    LEAVE_DESCRIPTION TEXT DEFAULT NULL,
    STATUS_OF_LEAVE VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (LEAVE_ID),
    INDEX idx_employee_id (EMPLOYEE_ID),
    INDEX idx_leave_type (LEAVE_TYPE),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);


-- CREATE TABLE LEAVE_TYPES
CREATE TABLE LEAVE_TYPES (
    LEAVE_TYPE VARCHAR(50) NOT NULL,
    ALLOWED_DAYS VARCHAR(20) DEFAULT NULL,
    GENDER_ELIGIBILITY ENUM('ALL', 'MALE', 'FEMALE') NOT NULL,
    PRIMARY KEY (LEAVE_TYPE)
);



-- CREATE TABLE HOLIDAYS
CREATE TABLE HOLIDAYS (
    HOLIDAY_ID INT NOT NULL AUTO_INCREMENT,
    HOLIDAY_NAME VARCHAR(50) NOT NULL,
    DAY VARCHAR(20) NOT NULL,
    HOLIDAY_DATE DATE NOT NULL,
    PRIMARY KEY (HOLIDAY_ID)
);







